.PHONY: all check pro

all: check propuesta.pdf

check: | vendor vendor/bundle
	@scripts/check-pandoc.sh
	@scripts/check-bundler.sh

vendor:
	@composer install

vendor/bundle:
	@bundle install --path vendor/bundle

propuesta.pdf: requisitos.xls propuesta.md
	@php scripts/requisitos.php
	@pandoc -f markdown-smart -s propuesta.md requisitos.md -o pro.adoc
	@scripts/replace.sh
	@echo "Generando propuesta.pdf..."
	@bundle exec asciidoctor-pdf propuesta.adoc
	@rm -f pro.adoc propuesta.adoc
